INSERT OR IGNORE INTO categories (id, slug, name, name_ar) VALUES
  (1, 'signature-honey', 'Signature Honey', 'عسل فاخر'),
  (2, 'honey-blends', 'Honey Blends', 'خلطات العسل'),
  (3, 'gifts', 'Gift Editions', 'هدايا أصلنا');

INSERT OR IGNORE INTO products (
  id, slug, name, name_ar, description, short_description, price, old_price, category_id, image, image_alt, stock, badge, rating, origin, floral_notes, benefits, featured, best_seller, raw_label, organic_label, limited_label
) VALUES
  (1, 'sidr-honey', 'Sidr Honey', 'عسل سدر', 'A rare Yemeni-inspired Egyptian sidr harvest with deep body, resin warmth, and a luxurious finish built for slow tasting.', 'Dense, rare, gift-worthy sidr honey with a deep amber body.', 420, 480, 1, '/assets/images/sidr-honey.svg', 'Sidr honey jar', 26, 'Limited', 4.9, 'Siwa desert bloom', 'Resin, toasted blossom, warm wood', 'Raw energy, naturally rich texture, premium gifting appeal', 1, 1, 1, 1, 1),
  (2, 'clover-honey', 'Clover Honey', 'عسل البرسيم', 'Silky clover honey with an airy floral aroma and clean sweetness made for breakfasts, pastries, and tea rituals.', 'Lighter floral honey with a polished everyday finish.', 220, 260, 1, '/assets/images/raw-honey.svg', 'Clover honey jar', 40, 'Raw', 4.7, 'Nile Delta clover fields', 'White blossom, soft hay, vanilla', 'Daily immunity support, smooth sweetness, breakfast pairing', 1, 0, 1, 1, 0),
  (3, 'black-seed-honey', 'Black Seed Honey', 'عسل الحبة السوداء', 'A darker therapeutic-style blend where pure honey meets black seed character for a bold, wellness-forward spoon.', 'Powerful blend with a deeper aromatic edge.', 310, NULL, 2, '/assets/images/black-seed-honey.svg', 'Black seed honey jar', 28, 'Organic', 4.8, 'Upper Egypt black seed farms', 'Warm spice, dry herbs, roasted depth', 'Balanced warmth, strong aroma, wellness-led profile', 1, 1, 0, 1, 0),
  (4, 'mountain-honey', 'Mountain Honey', 'عسل جبلي', 'Harvested from elevated wildflower zones for a layered mineral profile, darker sweetness, and slower finish.', 'Earthy, mineral-rich mountain harvest.', 295, 340, 1, '/assets/images/mountain-honey.svg', 'Mountain honey jar', 22, 'Best Seller', 4.9, 'South Sinai heights', 'Wild thyme, stone fruit, cedar', 'Mineral depth, cold extracted, distinct aftertaste', 1, 1, 1, 0, 0),
  (5, 'citrus-blossom-honey', 'Citrus Blossom Honey', 'عسل زهر الحمضيات', 'Bright citrus blossom honey with a lifted aroma and a refined finish that feels crisp rather than sugary.', 'Fresh blossom honey with a bright aromatic lift.', 245, NULL, 1, '/assets/images/citrus-honey.svg', 'Citrus blossom honey jar', 35, 'Fresh Drop', 4.8, 'Sharqia citrus groves', 'Orange flower, zest, white tea', 'Fresh aroma, versatile pairing, soft sweetness', 0, 0, 1, 1, 0),
  (6, 'royal-honey-mix', 'Royal Honey Mix', 'رويال هاني ميكس', 'A ceremonial spoon blending premium honey with royal-style fortifying ingredients for a richer lifestyle-focused product.', 'Dense blend designed for focused daily rituals.', 520, 590, 2, '/assets/images/hero-honey.svg', 'Royal honey mix', 18, 'Premium', 4.9, 'Curated Egyptian blend', 'Dark blossom, pollen, date molasses', 'Luxury wellness blend, spoon texture, elevated gifting', 0, 1, 0, 1, 1),
  (7, 'honeycomb-box', 'Honeycomb Edition', 'شمع العسل', 'Cut honeycomb presented like an edible jewel: raw cell structure, natural drip, and a visually unforgettable serving moment.', 'Raw honeycomb for premium serving and hosting.', 390, NULL, 3, '/assets/images/hero-honey.svg', 'Honeycomb box', 14, 'Raw', 4.8, 'Canal-side apiaries', 'Wax cell, bright nectar, warm pollen', 'Raw comb texture, hosting centerpiece, premium plating', 0, 0, 1, 1, 1),
  (8, 'asalna-gift-box', 'Asalna Gift Box', 'بوكس أصلنا', 'A curated gift edition with signature jars arranged in an artful premium box for weddings, corporate gifting, and seasonal drops.', 'Curated honey gift set with premium presentation.', 890, 980, 3, '/assets/images/facebook-cover.png', 'Asalna premium gift box', 10, 'Limited', 5.0, 'Curated across Egypt', 'Mixed floral library', 'Premium gifting, curated selection, memorable unboxing', 1, 1, 0, 0, 1);

INSERT OR IGNORE INTO admin_users (id, username, password_hash, display_name) VALUES
  (1, 'admin', 'c8a79ceaab80ba0c9718436665e092f611dbe4c8f01035ae89a3f414c3e9e116', 'Asalna Admin');
